[package]
name = "sigmaRs"
version = "0.1.0"
edition = "2021"

[dependencies]
argparse = "0.2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.128"
serde_yaml = "0.9.34"
walkdir = "2.5.0"
